Repository wecode-bootcamp-korea/43-1st-MG-frontend, pull requests merged in 2023-03, with the labels that each got.

#1 [43기 김진평] Nav 컴포넌트 구현 (1차 피드백 반영)
  src/Router.js
  src/assets/images/nav/home-logo.svg
  src/assets/images/nav/menu.png
  src/assets/images/nav/search.png
  src/assets/images/nav/shopping-bag.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#2 [43기 김진평] footer 1차 피드백 반영
  src/assets/images/footer/kakao-talk.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#3 [43기 문은빈] MODIFY: Signup 3차 피드백 반영수정완료
  src/pages/ShoppingBasket/ShoppingBasket.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/signupInPutList.js
  src/styles/mixin.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청, 리뷰 진행 중

#4 [43기 오지수] UPDATE: 로그인 페이지 2차PR 수정완료
  src/Router.js
  src/assets/images/plover.png
  src/assets/images/question.png
  src/assets/images/share.png
  src/components/Modal/Modal.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#5 [43기 문은빈] MODIFY: 장바구니 피드백 1차 반영 및 전체삭제 기능, fetch 작성
  public/data/data.json
  public/images/product.png
  src/assets/images/close.png
  src/assets/images/cross.png
  src/assets/images/shopping-cart.png
  src/pages/ShoppingBasket/ShoppingBasket.js
  src/pages/ShoppingBasket/ShoppingBasket.scss
  src/pages/ShoppingBasket/component/Product.js
  src/pages/ShoppingBasket/component/Product.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/signupInPutList.js
  src/styles/mixin.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청

#6 [43기 김진평] Main 컴포넌트 구현 및 네비게이션 내 카테고리 동적 라우팅과 무한 스크롤, 검색기능 추가
  public/data/productsData0&0&10.json
  public/data/productsData0&10&10.json
  public/data/productsData0&20&10.json
  public/data/productsData1&0&10.json
  public/data/productsData1&10&10.json
  public/data/productsData1&20&10.json
  public/data/productsData2&0&10.json
  public/data/productsData2&10&10.json
  public/data/productsData2&20&10.json
  public/data/productsData3&0&10.json
  public/data/productsData3&10&10.json
  public/data/productsData3&20&10.json
  public/data/slideData.json
  public/images/products/sampleImg1.jpg
  public/images/products/sampleImg10.jpg
  public/images/products/sampleImg2.jpg
  public/images/products/sampleImg3.jpg
  public/images/products/sampleImg4.jpg
  public/images/products/sampleImg5.jpg
  public/images/products/sampleImg6.jpg
  public/images/products/sampleImg7.jpg
  public/images/products/sampleImg8.jpg
  public/images/products/sampleImg9.jpg
  public/images/slide/img01.png
  public/images/slide/img02.png
  public/images/slide/img03.png
  public/images/slide/img04.png
  public/images/slide/img05.png
  src/Router.js
  src/assets/images/main/basket.png
  src/assets/images/nav/weekly.png
  src/assets/images/nav/weekly2.png
  src/assets/images/slide/left-arrow.png
  src/assets/images/slide/right-arrow.png
  src/components/Footer/Footer.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/ImgSlide/ImgSlide.js
  src/pages/Main/ImgSlide/ImgSlide.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Product/Product.js
  src/pages/Main/Product/Product.scss
  src/pages/Main/ProductList/ProductList.js
  src/pages/Main/ProductList/ProductList.scss
  src/styles/reset.scss
  src/styles/variables.scss
Labels: Conflict 해결 요청, 완료

#9 [43기 오지수] UPDATE: 로그인 페이지 3차 PR반영
  src/components/Modal/components/DetailOrder/DetailOrder.scss
  src/pages/Login/Login.js
  src/pages/ProductDetail/ProductOptionPrice/ProductOption.js
Labels: 멘토 리뷰 요청

#7 [43기 김진평] ADD : Modal UI 구현 및 메인페이지 장바구니 아이콘 클릭시 나타나는 MainCart 컴포넌트 구현
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/components/MainCart/MainCart.js
  src/components/Modal/components/MainCart/MainCart.scss
  src/functions/commonFunc.js
Labels: 완료

#10 ADD : 홈 로고 변경 및 페이지 로드시 장바구니 리스트 불러와 장바구니 아이콘 옆 개수 표시
  src/assets/images/nav/weeklyLogo.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#8 [43기 문은빈] ADD: 장바구니 내 구매하기 modal 창 구현
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/components/MainCart/MainCart.js
  src/components/Modal/components/MainCart/MainCart.scss
  src/components/Modal/components/Order/Order.js
  src/components/Modal/components/Order/Order.scss
  src/components/Nav/Nav.scss
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#11 [43기 문은빈 ] Signup 페이지 재업로드 파일 추가
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/signupInPutList.js
Labels: 멘토 리뷰 요청

#13 [43기 김진평] ADD : config.js에 API address 설정
  src/components/Modal/components/Order/Order.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/ShoppingBasket/ShoppingBasket.js
  src/pages/ShoppingBasket/component/Product.js
  src/pages/SignUp/SignUp.js
Labels: 수정 요청

#14 [43기 김진평] ADD : 장바구니 추가 백엔드 통신 및 장바구니 리스트 변경되었을 때 네비게이션 우측 장바구니 아이콘에 수량 변경되도록 수정
  src/components/Modal/components/MainCart/MainCart.js
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
  src/pages/Main/Product/Product.js
  src/pages/Main/ProductList/ProductList.js
Labels: 멘토 리뷰 요청

#15 [43기 김진평] MODIFY : 메인페이지 슬라이드 이미지 변경
  public/data/productsData0&0&10.json
  public/data/productsData0&10&10.json
  public/data/productsData0&20&10.json
  public/data/productsData1&0&10.json
  public/data/productsData1&10&10.json
  public/data/productsData1&20&10.json
  public/data/productsData2&0&10.json
  public/data/productsData2&10&10.json
  public/data/productsData2&20&10.json
  public/data/productsData3&0&10.json
  public/data/productsData3&10&10.json
  public/data/productsData3&20&10.json
  public/data/slideData.json
  public/images/slide/img01.jpg
  public/images/slide/img02.jpg
  public/images/slide/img03.jpg
  public/images/slide/img04.jpg
  public/images/slide/img05.jpg
Labels: 멘토 리뷰 요청

#16 [43기 문은빈] 구매하기 modal창 수정 및 장바구니 내 결제금액 계산 로직 수정
  public/data/cartListData.json
  public/data/data.json
  src/assets/images/delivery-truck.png
  src/components/Modal/Modal.js
  src/components/Modal/components/Order/Order.js
  src/components/Modal/components/Order/Order.scss
  src/config.js
  src/pages/ShoppingBasket/ShoppingBasket.js
  src/pages/ShoppingBasket/ShoppingBasket.scss
  src/pages/ShoppingBasket/component/Product.js
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청
